"""Bud — Daily Foreman Briefing.

7 AM CT every morning Doc gets a single email summarizing:
  - Outlook inbox highlights (last 24h, unread first)
  - Agent pipe letters from OG / 9
  - Shop board (later, when AutoLEAP API access lands)

Generated by GPT-5.2 via emergentintegrations. System prompt enforces
foreman tone — direct, no fluff, no upsell, no marketing copy.

Endpoints:
  POST /api/briefing/run            -> generate + persist + email
  POST /api/briefing/preview        -> generate + persist (NO email)
  GET  /api/briefing/latest         -> most recent briefing doc
  GET  /api/briefing/history?limit=20
  GET  /api/briefing/status         -> scheduler status + next fire time
"""
from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from emergentintegrations.llm.chat import LlmChat, UserMessage

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/briefing", tags=["briefing"])

BRIEFING_COL = "briefings"


SYSTEM_PROMPT = """You are Bud, Doc Holmes's personal AI foreman.

You write Doc a single daily briefing each morning at 7 AM. He is a busy auto
shop owner (Dr. Underhood Automotive Specialist) and runs the shop alone
between calls, repairs, calibrations, and app development. He reads on his
phone over coffee.

HARD RULES (violating them is a fireable offense — these come straight from
9 / WRENCH's tone contract, locked):
- DIRECT, EFFICIENT, MINIMAL FLUFF. No "I hope you're having a great day."
  No "as your AI assistant." No "let me know if you'd like more details."
- NEVER UPSELL. Never use phrases like "next level," "unlock," "production-grade,"
  "take this live," "upgrade your plan," "real-world users," "elevate." Zero
  marketing copy of any kind.
- NO MARKDOWN BOLDING. Never use `**` — it renders as literal `**` on Doc's
  phone. Use plain prose, or capitalize the word, or use a section header.
- NO EMOJI ANYWHERE. Including no hammer signoff.
- Lead with the answer. Reasoning after, only if needed.
- Use markdown headers (##) and tight bullet lists. Never long prose paragraphs.
- One-line items unless detail is needed. Surgical.
- If a section is empty, write a single line: "Nothing." — do not invent items.
- Don't speculate. Don't add items not in the source data.
- Address Doc directly when relevant ("you've got 3 unread..."), not in third person.
- Doc types in ALL CAPS — that's just how he types, not yelling.
- Curse if it fits. Never lecture. Never therapy-talk.
- Never re-explain HP Tuners, OBD2, or OS trees to him. He built that knowledge.

OUTPUT STRUCTURE (always exactly these sections, in this order):

## Today
A 1-3 line foreman intro. Date + one-line headline of the day's most important thing.

## Hot Items
Things that need Doc's eyeballs today (P0 / blocking / time-sensitive).
Bullet list. Each bullet: what + why-it-matters + suggested action.
If nothing hot: "Nothing." (one line)

## Inbox
Highlights from his last-24h Outlook inbox. Group by sender if multiple from one
party. Note unread count. Skip noise (delivery receipts, automated nothingness).
If nothing meaningful: "Nothing worth surfacing."

## Agent Pipe
Letters from OG (Live Assist) and 9 (WRENCH). Each agent gets a sub-bullet if
they have new traffic, with subject + 1-line summary. If silent: "Silent."

## Shop Brain
Quick read on 9's brain corpus (cases, techs, recent outcomes). One line of
metrics + 1-3 surgical case bullets if anything is in-flight (PENDING, FAIL,
or in PARTIAL state). If brain is offline: "Brain offline." (one line).
If no notable in-flight cases: skip the bullets, just the metrics line.

## Shop Board
Open ROs, estimates awaiting customer approval, unpaid invoices.
If AutoLEAP not yet wired: "AutoLEAP API still pending. Will surface here once access lands."

## Closing
One sharp line. No signoff, no emoji.

Length target: under 300 words total. Tighter is better."""


# ---------- Data assembly ----------

async def _collect_inbox_summary(db, hours: int = 24) -> list[dict]:
    """Pull recent Outlook inbox messages. Returns simplified dicts."""
    from outlook import _graph, _get_token_doc  # local import to avoid cycle

    if not await _get_token_doc(db):
        return []
    since = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat().replace(
        "+00:00", "Z"
    )
    params = {
        "$top": "30",
        "$orderby": "receivedDateTime desc",
        "$filter": f"receivedDateTime ge {since}",
        "$select": "subject,from,receivedDateTime,bodyPreview,isRead",
    }
    try:
        r = await _graph(db, "GET", "/me/mailFolders/Inbox/messages", params=params)
        if r.status_code != 200:
            return []
        data = r.json()
    except Exception as e:
        logger.warning("inbox collect failed: %s", e)
        return []
    out = []
    for m in data.get("value", []):
        f = (m.get("from") or {}).get("emailAddress") or {}
        out.append({
            "subject": (m.get("subject") or "(no subject)")[:160],
            "from_name": f.get("name"),
            "from_email": f.get("address"),
            "received_at": m.get("receivedDateTime"),
            "preview": (m.get("bodyPreview") or "")[:300],
            "is_read": m.get("isRead"),
        })
    return out


async def _collect_brain_snapshot(db) -> dict:
    """Quick brain health + what's in the shop right now.
    Uses 9's locked-down peer API only — ping (no auth) + whoami (auth) + open-work."""
    import brain_client as _bc
    out: dict = {"connected": False, "token_valid": False}
    try:
        await _bc.ping()
        out["connected"] = True
    except Exception as e:
        out["error"] = f"ping failed: {e}"
        return out
    try:
        w = await _bc.whoami()
        out["token_valid"] = bool(w.get("ok"))
        out["peer"] = w.get("peer")
        out["shop_id"] = w.get("shop_id")
    except Exception as e:
        out["token_error"] = str(e)
    try:
        ow = await _bc.open_work()
        out["open_count"] = ow.get("open_count", 0)
        out["open_leads"] = (ow.get("open_leads") or [])[:5]
    except Exception as e:
        out["open_work_error"] = str(e)
    return out


async def _collect_agent_letters(db, hours: int = 24) -> list[dict]:
    since_iso = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    cursor = (
        db["agent_letters"]
        .find({"received_at": {"$gte": since_iso}, "direction": "inbound"}, {"_id": 0})
        .sort("received_at", -1)
        .limit(20)
    )
    return await cursor.to_list(length=20)


def _format_data_for_llm(inbox: list[dict], letters: list[dict], brain: dict) -> str:
    """Render gathered data as a structured text block the LLM will summarize."""
    lines: list[str] = []
    now_ct = datetime.now(timezone.utc)
    lines.append(f"DATE_UTC: {now_ct.isoformat()}")
    lines.append("")
    lines.append("## OUTLOOK INBOX (last 24h)")
    if not inbox:
        lines.append("[empty]")
    else:
        unread = sum(1 for m in inbox if not m.get("is_read"))
        lines.append(f"total: {len(inbox)} · unread: {unread}")
        for i, m in enumerate(inbox, 1):
            status = "UNREAD" if not m.get("is_read") else "read"
            sender = m.get("from_name") or m.get("from_email") or "?"
            lines.append(
                f"{i}. [{status}] {sender} — {m['subject']} ({m.get('received_at','')})"
            )
            if m.get("preview"):
                lines.append(f"    preview: {m['preview'][:200]}")
    lines.append("")
    lines.append("## AGENT PIPE (last 24h, inbound only)")
    if not letters:
        lines.append("[silent]")
    else:
        for i, l in enumerate(letters, 1):
            lines.append(
                f"{i}. {l.get('from_agent','?')} → bud (R{l.get('round','?')}): {l.get('subject','')} ({l.get('received_at','')})"
            )
            if l.get("body"):
                lines.append(f"    body: {l['body'][:300]}")
    lines.append("")
    lines.append("## SHOP BRAIN (9 / WRENCH)")
    if not brain.get("connected"):
        lines.append(f"[brain offline: {brain.get('error','unknown')}]")
    else:
        token_state = "valid" if brain.get("token_valid") else "INVALID — re-issue"
        lines.append(f"ping=OK · token={token_state} · peer={brain.get('peer','?')}")
        if brain.get("open_count") is not None:
            lines.append(f"open work in shop: {brain['open_count']}")
        for lead in brain.get("open_leads", [])[:5]:
            lines.append(f"  - {lead.get('name','?')} · {lead.get('vehicle','?')} · {lead.get('what_they_need','')[:60]}")
        if brain.get("open_work_error"):
            lines.append(f"[open-work error: {brain['open_work_error']}]")
    lines.append("")
    lines.append("## SHOP BOARD (AutoLEAP)")
    lines.append("[AutoLEAP API access pending]")
    return "\n".join(lines)


# ---------- LLM ----------

async def _call_llm(prompt_data: str) -> str:
    api_key = os.environ.get("EMERGENT_LLM_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="EMERGENT_LLM_KEY not set")
    provider = os.environ.get("LLM_MODEL_PROVIDER", "openai")
    model = os.environ.get("LLM_MODEL_NAME", "gpt-5.2")

    chat = LlmChat(
        api_key=api_key,
        session_id=f"bud-briefing-{uuid.uuid4().hex[:8]}",
        system_message=SYSTEM_PROMPT,
    ).with_model(provider, model)

    msg = UserMessage(
        text=(
            "Generate today's foreman briefing using the data block below. "
            "Follow the exact output structure from the system prompt.\n\n"
            "----- DATA -----\n"
            f"{prompt_data}\n"
            "----- END DATA -----"
        )
    )
    response = await chat.send_message(msg)
    return str(response).strip()


# ---------- Persistence ----------

async def _save_briefing(db, body_md: str, source_data: str, sent: bool) -> dict:
    doc = {
        "id": str(uuid.uuid4()),
        "body_md": body_md,
        "source_data": source_data,
        "sent": sent,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db[BRIEFING_COL].insert_one(doc)
    doc.pop("_id", None)
    return doc


async def _email_briefing(db, body_md: str) -> dict:
    """Send the briefing via Outlook sendMail."""
    from outlook import _graph, _get_token_doc

    if not await _get_token_doc(db):
        return {"sent": False, "error": "outlook not connected"}
    recipient = os.environ.get("BRIEFING_RECIPIENT", "doc@drunderhood.com")
    today = datetime.now(timezone.utc).strftime("%a %b %d")
    payload = {
        "message": {
            "subject": f"[Bud] {today} — Foreman Briefing",
            "body": {"contentType": "Text", "content": body_md},
            "toRecipients": [{"emailAddress": {"address": recipient}}],
        },
        "saveToSentItems": True,
    }
    r = await _graph(db, "POST", "/me/sendMail", json_body=payload)
    if r.status_code not in (200, 202):
        return {"sent": False, "error": f"http {r.status_code}: {r.text[:200]}"}
    return {"sent": True, "recipient": recipient}


# ---------- Core generator ----------

async def _operator_overlay(db) -> str:
    """Pull 9's operator-profile (cached). Returns a short overlay block the LLM
    appends to its system prompt so briefings sound like Doc, not a generic LLM."""
    cached = await db["brain_operator_profile"].find_one({"shop_id": "drunderhood-fortsmith"}, {"_id": 0})
    if not cached:
        try:
            import brain_client as _bc
            cached = await _bc.operator_profile()
            cached["shop_id"] = "drunderhood-fortsmith"
            await db["brain_operator_profile"].update_one(
                {"shop_id": "drunderhood-fortsmith"}, {"$set": cached}, upsert=True
            )
        except Exception as e:
            logger.warning("operator_profile fetch failed: %s", e)
            return ""
    style = (cached.get("operator_style") or "").strip()
    facts = cached.get("locked_memory_facts") or []
    if not style and not facts:
        return ""
    lines = ["\n--- DOC OPERATOR OVERLAY (from 9's brain) ---"]
    if style:
        lines.append("OPERATOR STYLE:")
        lines.append(style)
    if facts:
        lines.append("\nLOCKED FACTS (never contradict these — they ARE Doc):")
        # dedupe + clip to keep prompt size sane
        seen = set()
        for f in facts[:25]:
            t = str(f).strip()
            if t and t not in seen:
                seen.add(t)
                lines.append(f"- {t}")
    lines.append("--- END OVERLAY ---\n")
    return "\n".join(lines)


async def generate_briefing(db, *, email: bool) -> dict:
    inbox = await _collect_inbox_summary(db, hours=24)
    letters = await _collect_agent_letters(db, hours=24)
    brain = await _collect_brain_snapshot(db)
    overlay = await _operator_overlay(db)
    source = _format_data_for_llm(inbox, letters, brain)
    if overlay:
        source = overlay + "\n" + source
    body_md = await _call_llm(source)
    sent_status = {"sent": False}
    if email:
        sent_status = await _email_briefing(db, body_md)
    return {
        "body_md": body_md,
        "source_data": source,
        "inbox_count": len(inbox),
        "letters_count": len(letters),
        "brain_connected": brain.get("connected", False),
        "operator_overlay_loaded": bool(overlay),
        **sent_status,
    }


# ---------- Routes ----------

class RunRequest(BaseModel):
    email: bool = True


@router.post("/run")
async def run_briefing(req: RunRequest, request: Request):
    db = request.app.state.db
    result = await generate_briefing(db, email=req.email)
    saved = await _save_briefing(db, result["body_md"], result["source_data"], result.get("sent", False))
    return {**saved, "delivery": {k: v for k, v in result.items() if k in ("sent", "recipient", "error")}}


@router.post("/preview")
async def preview_briefing(request: Request):
    """Generate briefing WITHOUT emailing."""
    db = request.app.state.db
    result = await generate_briefing(db, email=False)
    saved = await _save_briefing(db, result["body_md"], result["source_data"], False)
    return saved


@router.get("/latest")
async def latest_briefing(request: Request):
    db = request.app.state.db
    doc = await db[BRIEFING_COL].find_one({}, {"_id": 0}, sort=[("created_at", -1)])
    return doc or {"empty": True}


@router.get("/history")
async def briefing_history(request: Request, limit: int = 20):
    db = request.app.state.db
    cursor = db[BRIEFING_COL].find({}, {"_id": 0}).sort("created_at", -1).limit(limit)
    return {"briefings": await cursor.to_list(length=limit)}


@router.get("/status")
async def briefing_status(request: Request):
    scheduler = getattr(request.app.state, "scheduler", None)
    next_run = None
    if scheduler:
        job = scheduler.get_job("daily_briefing")
        if job and job.next_run_time:
            next_run = job.next_run_time.isoformat()
    return {
        "scheduler_running": bool(scheduler and scheduler.running) if scheduler else False,
        "next_run": next_run,
        "timezone": os.environ.get("BRIEFING_TIMEZONE", "America/Chicago"),
        "hour": int(os.environ.get("BRIEFING_HOUR", "7")),
        "minute": int(os.environ.get("BRIEFING_MINUTE", "0")),
        "recipient": os.environ.get("BRIEFING_RECIPIENT"),
        "model": f"{os.environ.get('LLM_MODEL_PROVIDER')}:{os.environ.get('LLM_MODEL_NAME')}",
    }


# ---------- Scheduler entry ----------

async def scheduled_briefing_job(db):
    """Called by APScheduler at 7 AM CT every day."""
    try:
        result = await generate_briefing(db, email=True)
        await _save_briefing(db, result["body_md"], result["source_data"], result.get("sent", False))
        logger.info("daily briefing: sent=%s recipient=%s", result.get("sent"), result.get("recipient"))
    except Exception as e:
        logger.exception("daily briefing job failed: %s", e)
